name: Ubuntu
on:
  push:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - '.github/workflows/Ubuntu.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - '.github/workflows/Ubuntu.yml'
  workflow_dispatch:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - '.github/workflows/Ubuntu.yml'



jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt-get install -y  build-essential automake libtool libevent-dev libncurses5-dev libmsgpack-dev libssh-dev pkg-config
        autoupdate
        ACLOCAL_PATH=/usr/share/aclocal ./autogen.sh
        ./configure
        make
        sudo make install
    - name: Upload a tamte Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: tmate
        path: tmate        
    - name: Download a tmate Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: tmate
        path: tmate
